/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        cli("input","output","transform");}

    public static void cli(String input, String output, String transform){
        System.out.println(input);
        System.out.println(output);
        System.out.println(transform);

    }
}


