/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        cli("resources/java_clr_hori.bmp","resources/test.bmp","transform");}

    public static void cli(String input, String output, String transform){
        System.out.println(input);
        System.out.println(output);
        System.out.println(transform);

        BufferedImage out = null;

        try{
            File inputFile = new File(input);
            out = ImageIO.read(inputFile);

        }catch(IOException e){
            System.out.println(e);
        }

        try {
            File outputFile = new File(output);
            ImageIO.write(out,"bmp",outputFile );
        }catch(IOException e){
            System.out.println(e);
        }

        }

    }




